In [1]:
import numpy as np

In [4]:
arr=np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [25]:
print(arr[0:7:2])#initial(inclusive) and final(exclusive) and steps

[11 13 15 17]


In [27]:
arr1=np.arange(1,31).reshape(6,5)
print(arr1)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]]


In [32]:
print(arr1[3:,3:])

[[19 20]
 [24 25]
 [29 30]]


In [35]:
bool_index=arr%2==0
arr=arr[bool_index]
arr

array([12, 14, 16, 18, 20])